version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: david
      RABBITMQ_DEFAULT_PASS: '9896'
      RABBITMQ_DEFAULT_VHOST: /
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app_net
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=PathPrefix(`/monitor`)"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
      - "traefik.http.routers.rabbitmq.entrypoints=web"
      - "traefik.http.middlewares.monitor-stripprefix.stripprefix.prefixes=/monitor"
      - "traefik.http.routers.rabbitmq.middlewares=monitor-stripprefix"

  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: david
      RABBITMQ_PASS: '9896'
    networks:
      - app_net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.api.middlewares=api-stripprefix"
    depends_on:
      rabbitmq:
        condition: service_healthy

  worker:
    build: ./worker
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USER: david
      RABBITMQ_PASS: '9896'
    volumes:
      - messages_data:/app/messages
    networks:
      - app_net
    depends_on:
      rabbitmq:
        condition: service_healthy

  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app_net

volumes:
  rabbitmq_data:
  messages_data:

networks:
  app_net:
    driver: bridge